### ISSUE TITLE
how do I use this library with jest testing?

### ISSUE THREAD

**Issue by rainzhao2000** [dsherret/conditional-type-checks#5]
I want to compare two interfaces and write runtime tests based on the result.
`type IDialogUnchanged = IsExact<IDialog, IDialogOrig>;`
I have that so far but I am unsure of how to turn that into a variable I can check at runtime.

**Comment by dsherret** [comment]
Hey @rainzhao2000, all tests for this library happen at compile time rather than runtime, so in order to test this you only need to run `tsc`. If it compiles that means the tests pass.

Is what you're wanting something where it takes some code like `IsExact<IDialog, IDialogOrig>` and transforms it to `true` or `false`? That would require a compiler plugin using custom transforms and is beyond the scope of this library.

**Comment by rainzhao2000** [comment]
Thank you for the quick response, what is tsc?

**Comment by rainzhao2000** [comment]
Do you think I should be looking into ts-jest about my request? Do you have any tips on how I can write runtime tests for interfaces?

**Comment by dsherret** [comment]
@rainzhao2000 `tsc` is the typescript compiler. So I meant you only need to compile to test (ex. running the command [`tsc`](https://www.typescriptlang.org/docs/tutorial.html#compiling-your-code)).

I don't think ts-jest will help you in this scenario. Could you show some example code of how you would like to write "runtime tests for interfaces"? Note that interfaces disappear when compiling, but maybe there's a way to test what you want to do with this library or perhaps I could improve it to help your situation.

**Comment by rainzhao2000** [comment]
I am using StencilJS and they use Jest and Typescript. I want to write a test that checks if an interface has changed, specifically if two interfaces are equal.

**Comment by dsherret** [comment]
So you could write:

```ts
import { AssertTrue, IsExact } from "conditional-type-checks";

type assertDialogUnchanged = AssertTrue<IsExact<IDialog, IDialogOrig>>;
```

Or alternatively:

```ts
import { assert, IsExact } from "conditional-type-checks";

assert<IsExact<IDialog, IDialogOrig>>(true);
```

Then try changing one of the interfaces. You should get a compile error if they're not exact. I think ts-jest might fail running if this fails... I'm not sure if it continues running when there are compile errors.

---

Basically, once compiled to JavaScript, the interfaces will go away and there's no way to check them. That's why this library works at compile time, so you'll get compile errors at compile time for every failure, rather than runtime test errors.

**Comment by rainzhao2000** [comment]
I appreciate your patience, your library works as intended and I do get the compile errors. I guess I'm just confused why running jest tests don't seem to report these errors.

**Comment by dsherret** [comment]
Hmm... not sure why it's not reported by ts-jest. Seems like the diagnostics should be enabled by default: https://kulshekhar.github.io/ts-jest/user/config/diagnostics

Perhaps StencilJS disables diagnostics in ts-jest. They might do that because collecting diagnostics would slow down running the tests a little bit.

Anyway, as long as somewhere in your process you compile typescript and have compile errors reported, that should be sufficient. Another possibility is to have a separate script that does [`tsc --noEmit`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to ensure there's no compile errors... I'm not sure how nicely that plays with StencilJS though.

**Comment by rainzhao2000** [comment]
I was just going to update by saying I think you've been very helpful and have done what you can. You've helped me better recognize the issue and I will no longer trouble you unless it's related to this library.

**Comment by dsherret** [comment]
No problem, happy to help! :)
